In [176]:
import pandas as pd

In [177]:
path = "ElectionResults.csv"
ElectionResults = pd.read_csv(path, error_bad_lines=False, warn_bad_lines=False)
ElectionResults.head(2)

,State,Constituency,O.S.N.,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes
0,Andhra Pradesh,Aruku,1.0,KISHORE CHANDRA DEO,Telugu Desam,336163,1938,338101,31.46
1,Andhra Pradesh,Aruku,2.0,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,Bharatiya Janata Party,17578,289,17867,1.66

In [178]:
ElectionResults = ElectionResults.drop(['O.S.N.'], axis=1)
ElectionResults.head(5)

,State,Constituency,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,Telugu Desam,336163,1938,338101,31.46
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,Bharatiya Janata Party,17578,289,17867,1.66
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,Yuvajana Sramika Rythu Congress Party,557561,4629,562190,52.32
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,Indian National Congress,17656,74,17730,1.65
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,Janasena Party,42245,549,42794,3.98

In [180]:
ElectionResults_ST_UT = ElectionResults.groupby('State')
ElectionResults_ST_UT.get_group('Telangana').head(5)
# ElectionResults_ST_UT

,State,Constituency,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes
8262,Telangana,Adilabad,Godam Nagesh,Telangana Rashtra Samithi,318665,149,318814,29.97
8263,Telangana,Adilabad,RATHOD RAMESH,Indian National Congress,314057,181,314238,29.54
8264,Telangana,Adilabad,SOYAM BAPU RAO,Bharatiya Janata Party,376892,482,377374,35.48
8265,Telangana,Adilabad,KUMRAM VANDANA,Nava Praja Rajyam Party,8005,2,8007,0.75
8266,Telangana,Adilabad,Dharavath Narendhar Naik,Janasena Party,5233,8,5241,0.49

In [182]:
# ElectionResults_ST_UT_Party = ElectionResults.groupby(['State', 'Party'])
# ElectionResults_ST_UT_Party.get_group(('Andhra Pradesh', 'Telugu Desam')).head(5)
ElectionResults_ST_UT_Party = ElectionResults.groupby(['State', 'Party'])
ElectionResults_ST_UT_Party.get_group(('Telangana', 'Indian National Congress')).head(5)

,State,Constituency,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes
8263,Telangana,Adilabad,RATHOD RAMESH,Indian National Congress,314057,181,314238,29.54
8275,Telangana,Peddapalle,Agam Chandrasekhar,Indian National Congress,345955,186,346141,35.68
8294,Telangana,Karimnagar,Ponnam Prabhaker,Indian National Congress,179140,118,179258,15.62
8313,Telangana,Nizamabad,MADHU GOUD YASKHI,Indian National Congress,69173,67,69240,6.52
8500,Telangana,Zahirabad,MADAN MOHAN RAO,Indian National Congress,427900,115,428015,40.98

In [183]:
ElectionResults_ST_UT_Party.get_group(('Telangana', 'Indian National Congress')).head(5)

,State,Constituency,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes
8263,Telangana,Adilabad,RATHOD RAMESH,Indian National Congress,314057,181,314238,29.54
8275,Telangana,Peddapalle,Agam Chandrasekhar,Indian National Congress,345955,186,346141,35.68
8294,Telangana,Karimnagar,Ponnam Prabhaker,Indian National Congress,179140,118,179258,15.62
8313,Telangana,Nizamabad,MADHU GOUD YASKHI,Indian National Congress,69173,67,69240,6.52
8500,Telangana,Zahirabad,MADAN MOHAN RAO,Indian National Congress,427900,115,428015,40.98

In [184]:
ElectionResults_ST_UT_Const = ElectionResults.groupby(['State', 'Constituency'])
df_1 = ElectionResults_ST_UT_Const.get_group(('Telangana', 'Malkajgiri'))
df_1.reset_index(inplace=True)
df_1.head(12)

,index,State,Constituency,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes
0,8524,Telangana,Malkajgiri,ANUMULA REVANTH REDDY,Indian National Congress,602907,841,603748,38.63
1,8525,Telangana,Malkajgiri,RAJASHEKAR REDDY MARRI,Telangana Rashtra Samithi,592485,344,592829,37.93
2,8526,Telangana,Malkajgiri,RAMCHANDER RAO NARAPARAJU,Bharatiya Janata Party,303851,431,304282,19.47
3,8527,Telangana,Malkajgiri,CHAMAKURA RAJAIAH,Social Justice Party of India,1350,1,1351,0.09
4,8528,Telangana,Malkajgiri,DHARMASANAM BHANUMURTHY,Praja Satta Party,719,1,720,0.05
5,8529,Telangana,Malkajgiri,BALAMANI BURU,India Praja Bandhu Party,1233,3,1236,0.08
6,8530,Telangana,Malkajgiri,MAHENDER REDDY BONGUNOORI,Janasena Party,28413,7,28420,1.82
7,8531,Telangana,Malkajgiri,CHALIKA CHANDRA SEKHAR,Independent,1178,2,1180,0.08
8,8532,Telangana,Malkajgiri,THIRUPATAIAH ENDURAM,Independent,3750,0,3750,0.24
9,8533,Telangana,Malkajgiri,DONTHULA BIKSHAPATHI,Independent,3307,1,3308,0.21
10,8534,Telangana,Malkajgiri,RAJENDER PONNALA,Independent,2680,0,2680,0.17
11,8535,Telangana,Malkajgiri,SAI KIRAN GONE,Independent,1660,4,1664,0.11

In [185]:
# df_1['EVM Votes'][0:10].max()
max_index = df_1['Total Votes'].idxmax()
# max_index
df_1['Total Votes'][0:max_index].max()

603748